on:
  workflow_dispatch:

jobs:
  shared-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up Java
        id: setup
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: temurin
          java-version: 21
  scala-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install sbt
        id: 'sbt'
        uses: sbt/setup-sbt@7106bdca9eae3f592a8baeccf57b5a3e06c0de5f # v1.1.14
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@f43202114d7522a4b233e052f82c2eea8d658134 # v3.2.1
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
  kotlin-job:
    runs-on: ubuntu-latest
    steps:
      - name: Submit dependencies
        id: submit
        uses: gradle/actions/dependency-submission@f236b35da9d031e13b1005234ebe4392ed54c580 # v5.0.0
      - name: Log snapshot for user validation
        id: validate
        run: cat "$GITHUB_WORKSPACE/dependency-graph-reports/update_dependency_graph_for_gradle-dependency-graph.json" | jq
